export const GET_KNOWLEDGE = 'GET_KNOWLEDGE'
export const GET_KNOWLEDGE_SUCCEEDED = 'GET_KNOWLEDGE_SUCCEEDED'
export const GET_KNOWLEDGE_FAILED = 'GET_KNOWLEDGE_FAILED'

export const ADD_KNOWLEDGE = 'ADD_KNOWLEDGE'
export const ADD_KNOWLEDGE_SUCCEEDED = 'ADD_KNOWLEDGE_SUCCEEDED'
export const ADD_KNOWLEDGE_FAILED = 'ADD_KNOWLEDGE_FAILED'

export const MOD_KNOWLEDGE = 'MOD_KNOWLEDGE'
export const MOD_KNOWLEDGE_SUCCEEDED = 'MOD_KNOWLEDGE_SUCCEEDED'
export const MOD_KNOWLEDGE_FAILED = 'MOD_KNOWLEDGE_FAILED'

export const DEL_KNOWLEDGE = 'DEL_KNOWLEDGE'
export const DEL_KNOWLEDGE_SUCCEEDED = 'DEL_KNOWLEDGE_SUCCEEDED'
export const DEL_KNOWLEDGE_FAILED = 'DEL_KNOWLEDGE_FAILED'

export const UPDATE_SSR_KNOWLEDGE = 'UPDATE_SSR_KNOWLEDGE'

export const SEARCH_KNOWLEDGE_BYID = 'SEARCH_KNOWLEDGE_BYID'
export const SEARCH_KNOWLEDGE_BYID_SUCCEEDED = 'SEARCH_KNOWLEDGE_BYID_SUCCEEDED'
export const SEARCH_KNOWLEDGE_BYID_FAILED = 'SEARCH_KNOWLEDGE_BYID_FAILED'

export const SEARCH_KNOWLEDGE = 'SEARCH_KNOWLEDGE'
export const SEARCH_KNOWLEDGE_SUCCEEDED = 'SEARCH_KNOWLEDGE_SUCCEEDED'
export const SEARCH_KNOWLEDGE_FAILED = 'SEARCH_KNOWLEDGE_FAILED'